# Generated by Django 5.1.1 on 2024-10-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_emailrecipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smtpaccount',
            old_name='sent_count',
            new_name='daily_sent_count',
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='smtp_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='total_sent_count',
            field=models.IntegerField(default=0),
        ),
    ]
